### ISSUE TITLE
Less 入门基础

### ISSUE THREAD

**Issue by pinggod** [pinggod/Blog#7]
> 实习团队需要使用 Less，所以整理一份留作备忘。

### 变量

```less
@color: #888;
h3 {
    color: @color + #222;
}
```

### 混合

```less
.boxShadow(@x:0,@y:0,@blur:1px,@color:#000){
    -moz-box-shadow: @arguments;
    -webkit-box-shadow: @arguments;
    box-shadow: @arguments;
}
#header {
    .boxShadow(2px,2px,3px,#f36);
}
```

### 模式匹配

```less
.mixin(light, @color) {
    color: #fff;
    background-color: @color;
}
.mixin(dark, @color) {
    color: #000;
    background-color: @color;
}
.mixin(@switcher, #eee) {
    font-weight: bold;    
}
.mixin(@switcher, @color) {
    display: block;
}
h1 {
    .mixin(light, #eee);
}
```

生成的 CSS: 

```css
h1 {
  color: #fff;
  background-color: #eeeeee;
  font-weight: bold;
  display: block;
}
```

### 导引表达式

导引表达式的关键字是 `when`，举例如下：

```less
.mixin (@a) when (lightness(@a) >= 50%) {
  background-color: black;
}
.mixin (@a) when (lightness(@a) < 50%) {
  background-color: white;
}
.mixin (@a) {
  color: @a;
}
.block {
    .mixin(#eee);
}
```

常用的运算符：`>`、`>=`、`=`、`<=`、`<`。

在 less 中，只有 `true` 表示真，其他值都表示假。

导引序列使用逗号分隔多个条件，必须同时满足所有的条件，才被视为匹配成功：

```less
.mixin (@a) when (@a > 10), (@a < -10) { ... }

@media: mobile;
.mixin (@a) when (@media = mobile) { ... }
.mixin (@a) when (@media = desktop) { ... }
.max (@a, @b) when (@a > @b) { width: @a }
.max (@a, @b) when (@a < @b) { width: @b }
```

还可以使用 less 的内置函数进行匹配，常见的检测函数包括：`iscolor`、`isnumber`、`isstring`、`iskeyword`、`isurl`。如果要判断一个值是纯数字还是单位量，可以使用`ispixel`、`ispercentage`、`isem`。

此外，可以使用 `not` 和 `and` 实现与或条件判断：

```less
.mixin (@a, @b: 0) when (isnumber(@b)) { ... }
.mixin (@a, @b: black) when (iscolor(@b)) { ... }

.mixin (@a) when (isnumber(@a)) and (@a > 0) { ... }
.mixin (@b) when not (@b > 0) { ... }
```

### 嵌套语法

```less
#header {
  color: black;
  .navigation {
    font-size: 12px;
  }
  .logo {
    width: 300px;
    &:hover { text-decoration: none }
  }
}
```

### 运算

任何数值、颜色和变量都可以参与运算：

```less
@base: 5%;
 @filler: @base * 2;
 @other: @base + @filler;
 
color: #888 / 4;
background-color: @base-color + #111;
height: 100% / 2 + @filler;
```

### 颜色函数

```less
lighten(@color, 10%);   
darken(@color, 10%);    
 
saturate(@color, 10%);  
desaturate(@color, 10%);
 
fadein(@color, 10%);    
fadeout(@color, 10%);   
fade(@color, 50%);      
 
spin(@color, 10);       
spin(@color, -10);      
 
mix(@color1, @color2);   
```

### 数学函数

```less
round(1.67); 
// => returns 2

ceil(2.4); 
// => returns 3

floor(2.6); 
// => returns 2

percentage(0.5) 
// => return 50%

sqrt(25cm) 
// => return 5cm

abs(-18.6%) 
// => return 18.6%

sin(1); 
// => sine of 1 radian 
// => return 0.8414709848078965;

asin(-0.8414709848078965) 
// => return -1rad

cos(1) 
// => cosine of 1 radian 
// => return 0.5403023058681398

pi() 
// => return 3.141592653589793
```

### 字符串函数

```less
replace("Hello, Mars?", "Mars\?", "Earth!");
// => "Hello, Earth!"

format-a-d: %("repetitions: %a file: %d", 1 + 2, "directory/file.less");
// => format-a-d: "repetitions: 3 file: "directory/file.less"";

escape('a=1') 
// => return a%3D1
```

### 导入文件

```less
@import "lib";

// less 不会处理导入的 css
@import "lib.css";
```

### 字符串插值

字符串插值形如 `@{name}`：

```less
@base-url: "http://assets.fnord.com";
background-image: url("@{base-url}/images/bg.png");
```

### 禁止编译

在字符串前添加 `~`，可以让 less 忽略它：

```less
.class {
  filter: ~"ms:alwaysHasItsOwnSyntax.For.Stuff()";
}
```

### JavaScript 表达式

使用反引号可以编写 JavaScript 表达式：

```less
@var: `"hello".toUpperCase() + '!'`;
// => @var: "HELLO!";
``
